server {
    listen 80;
    server_name localhost;
    root /var/www/html;
    index index.php index.html index.htm;

    charset utf-8;

    # Bloquear acceso a archivos de configuración y ocultos
    location ~ /\.(env|git|github|htaccess|editorconfig) {
        deny all;
    }

    # Bloquear bases de datos SQLite y logs
    location ~ \.(sqlite|sql|log)$ {
        deny all;
    }

    # Bloquear acceso directo a carpetas del sistema
    location ~ ^/(vendor|database|logs|cache|tests)/ {
        deny all;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Procesar archivos PHP con FastCGI (php-fpm)
    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass php:9000; # Nombre del servicio o socket php-fpm
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}
